### ISSUE TITLE
Support for TSB?

### ISSUE THREAD

**Issue by simonporter007** [jcul/HaliphaxHideRoot#2]
Worked brilliantly for Halifax, job well done, and I see you added support for Lloyd's. Don't suppose there's any chance of adding it for TSB? Seems to be pretty similar to Lloyd's from the outside.

Cheers,

**Comment by jcul** [comment]
Hi Simon,

Glad it's working for you.
Ya I'd imagine TSB would be very similar to Lloyds, I used to be a TSB
customer myself back before they split into Lloyds and TSB.

Will try have a look this week, if it is the same should be a 5 minute job
to add TSB!

Jack

**Comment by jcul** [comment]
I've just added support for TSB, it was using the same system as the others so was an easy change.

Sorry it took so long, been busy with a new job and I also changed phones and haven't had time to root my new one yet!

Haven't been able to try the TSB app because I'm not a customer, but I'm fairly confident it should work OK. If not let me know. It's in the Xposed repo now anyway.
